#!/bin/python3

name = input("What is your name? ")

def ChoiceTaker():
    choice = str(input("Hi, "name". \nWould you like me to do some math for you? \nType either y or n --|: ")).lower()

    if choice == "y":
        return InputOperation():

    elif choice == "n":
        print("Oh. Okay. Sorry to hear that, you math hating bitch.")
        print("Next time, stick to GIMP. --Later.")
        return exit()

    else:
        print("Do you know english, " + name + "?")
        return ChoiceTaker()

def InputOperation():
    ArithemeticString = str(input("Gimme sum math, bitch\n"))
    return ArithemeticString


def ArithemeticBuffer(ArithemeticString):
    OperationArray = list(ArithemeticString.split())
    return OperationArray


def BufferValidation(OperationArray):
    if OperationArray[1] != '+' or '-' or '*' or '/':
        print("Something fucked up; try REAL arithemetic...")
        return InputOperation()
    else: return OperationArray


def OperatorArray():
    return BufferValidation(ArithemeticBuffer(InputOperation()))


def InitCalculator():
    OperatorArray()
    A = OperationArray[0]
    OPERATOR = OperationArray[1]
    B = OperationArray[2]
    ANSWER = ArithemeticSolve(A, OPERATOR, B)
    return str("The answer is "+ str(ANSWER) + "\n \nOh and fuck YOU, " + str(name))

def ArithemeticSolve(IntegerA, Operator, IntegerB):
    A = int(IntegerA)
    B = int(IntegerB)
    if Operator == '+': return (A + B)
    elif Operator == '-': return (A - B)
    elif Operator == '*': return (A * B)
    else:
        if A % B == 0:
            return (A / B)
        else: return (float(A) / float(B))


